### PR TITLE
O&M for EM

### PR DESCRIPTION
**Pull request by asasr8**
This project has the details on how O&M services can be used to monitor the EM.

### CODE REVIEW

**Review by kgvarun — CHANGES_REQUESTED** [review]
@asasr8 @asasr8 there is a spelling mistake in the folder name 'knowlege-content' which was fixed in the base repo. Can update your fork to latest version and move your changes to the right directory.

**Review by kgvarun — CHANGES_REQUESTED** [review]
Log sources have to be xml not zip

**Comment by juergenfl** [comment]
> Log sources have to be xml not zip

Hi Kumar, zip is the exported format and can be used to import the log sources as well, I haven't seen any issue so far with importing them.

$ unzip -l 'EMCC OMS Logs_1726247312932.zip'
Archive:  EMCC OMS Logs_1726247312932.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     9542  09-13-2024 17:08   content.xml
      221  09-13-2024 17:08   README.txt
---------                     -------
     9763                     2 files
     
Or is it about importing them using CLI / API / Resource Manager ?

**Comment by juergenfl** [comment]
By the way, both Ashwini and I are members of the Oracle Organization, so the missing OCA should no longer be a blocker.

What is the solution for this? Do you have to reject/delete the pull request and we have to re-submit it?

**Comment by juergenfl** [comment]
Hi Kumar, just checked it, import needs files to be in zip format only, see screenshot:
Import-Configuration-Content

**Review by kgvarun — APPROVED** [review]

**Pull request merged**
